site_title: Anthony Atlas
favicon: ""
meta_description: Independent curator and consultant specializing in developing
  exhibitions, publications, archives, and artist legacy projects.
bio: Independent curator and consultant specializing in developing exhibitions,
  publications, archives, and artist legacy projects.
